workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == 'push'

image: python:3.12

stages:
    - test

before_script:
    pip install -r requirements.txt

unittest:
    stage: test
    tags:
        - students
    script:
        - pytest test_main.py

mypy:
    stage: test
    tags:
        - students
    script:
        - mypy .

black:
    stage: test
    tags:
        - students
    script:
        - black --diff --check .

isort:
    stage: test
    tags:
        - students
    script:
        - isort --check-only --diff --profile black .

flake8:
    stage: test
    tags:
        - students
    script:
        - flake8 .
