image: python:3.11

stages:
  - lint
  - test

before_script:
  - pip install -r requirements.txt
  - pip install flake8 isort black mypy pytest

lint:
  stage: lint
  script:
    - flake8 .
    - isort --check-only .
    - black --check .
    - mypy .

test:
  stage: test
  script:
    - pytest
