workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.12.5

stages:
  - build
  - test

before_script:
  - python -m venv myenv
  - source myenv/bin/activate
  - pip install -r requirements.txt

pytest:
  stage: test
  script:
    - source myenv/bin/activate
    - pytest -v tests

mypy:
  stage: test
  script:
    - source myenv/bin/activate
    - mypy src/

black:
  stage: test
  script:
    - source myenv/bin/activate
    - black --diff --check src/

isort:
  stage: test
  script:
    - source myenv/bin/activate
    - isort --check-only --diff --profile black src/

flake8:
  stage: test
  script:
    - source myenv/bin/activate
    - flake8 --max-line-length 99 src/