image: python:3.11

# Определение этапов
stages:
  - lint
  - test

# Установка зависимостей перед выполнением заданий
default:
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt  # Установка зависимостей проекта
    - pip install flake8 isort black mypy pytest factory-boy  # Установка линтеров и тестовых библиотек

# Задание для запуска линтеров
lint:
  stage: lint
  script:
    - flake8 app/  # Проверка кода на ошибки стиля
    - isort --check-only app/  # Проверка порядка импортов
    - black --check app/  # Проверка форматирования
    - mypy app/  # Проверка аннотаций типов

# Задание для запуска тестов
test:
  stage: test
  script:
    - pytest app/tests/  # Запуск тестов
