name: CI Pipeline

on:
  push:
    branches:
      - main  # Запуск при пушах в ветку main
  pull_request:
    branches:
      - main  # Запуск при создании Pull Request в ветку main

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.12  # Используем образ Python 3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонирует репозиторий

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Установка зависимостей из requirements.txt

      - name: Run Unit Tests
        run: |
          pytest test_main.py  # Запуск тестов с использованием pytest

      - name: Run MyPy
        run: |
          mypy .  # Проверка типизации с помощью MyPy

      - name: Run Black
        run: |
          black --diff --check .  # Проверка форматирования с помощью Black

      - name: Run Isort
        run: |
          isort --check-only --diff --profile black .  # Проверка сортировки импортов с использованием Isort и профиля Black

      - name: Run Flake8
        run: |
          flake8 .  # Статический анализ кода с Flake8
